# Spring boot server port set
server:
  port: 9090
  forward-headers-strategy: framework

# mariaDB 설정
spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    # DB Source URL
    url: jdbc:mariadb://localhost:3307/dodamdodam?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
    # DB username
    username: root
    # DB password
    password: ssafy
  # true 설정시 JPA 쿼리문 확인 가능
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    # DDL(create, alter, drop) 정의시 DB의 고유 기능을 사용할 수 있다.
    hibernate:
      ddl-auto: update
    # JPA의 구현체인 Hibernate가 동작하면서 발생한 SQL의 가독성을 높여준다.
    properties:
      hibernate.format_sql: true
# s3
cloud:
  aws:
    credentials:
      access-key: AKIAVPUXQSUO7G3OHJVQ   # IAM 계정의 accessKey
      secret-key: vE1QTu7yiFDN7Pq9/TW76lIONSrxZmq7uE9quHdp  # IAM 계정의 secretKey
    region:
      static: ap-northeast-2  # 버킷의 리전
    s3:
      bucket: dodamdodam   # 버킷 이름
    stack:
      auto: false
#swagger
#springfox:
#  documentation:
#    swagger:
#      v2:
#        path: /swagger/api-docs